module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    dirs:{
      jsSrc:'js',
      jsLibSrc:'js/lib',
      jsPluginsSrc:'js/plugins',
      jsCompiled:'compiled',
      jsCompiledApp:'compiled/app',
      jsDest:'public/scripts',
    },
    clean:['dest/*.js','docs','phpdocs','doc','deploy','app/database/seeds/SeedUsersTable.php','app/database/seeds/SeedExperiencesTable.php','deploy_fi','deploy_se','deploy_dk','deploy_no'],
    concat :{
      lib:{
        src:['<%= dirs.jsLibSrc %>/jquery.min.js','<%= dirs.jsLibSrc %>/bootstrap.min.js','<%= dirs.jsLibSrc %>/angular.min.js'],
        dest:'<%= dirs.jsDest %>/lib.min.js'
      },
      plugins:{
        src:['<%= dirs.jsPluginsSrc %>/*.js'],
        dest:'<%= dirs.jsCompiled %>/plugins.js',
      },
      modules:{
        src:['<%= dirs.jsSrc %>/app/*/*.js'],
        dest:'<%= dirs.jsCompiledApp %>/01.js'
      },
      services:{
        src:['<%= dirs.jsSrc %>/app/*/services/*.js'],
        dest:'<%= dirs.jsCompiledApp %>/02.js'
      },
      controllers:{
        src:['<%= dirs.jsSrc %>/app/*/controllers/*.js'],
        dest:'<%= dirs.jsCompiledApp %>/03.js'
      },
      directives:{
        src:['<%= dirs.jsSrc %>/app/*/directives/*.js'],
        dest:'<%= dirs.jsCompiledApp %>/04.js'
      },
      dev:{
        src:['<%= dirs.jsCompiledApp %>/*.js'],
        dest:'<%= dirs.jsDest %>/app.min.js'
      },
      deploy:{
        src:['<%= dirs.jsCompiledApp %>/*.js'],
        dest:'<%= dirs.jsCompiled %>/app.js'
      }
    },
    uglify: {
      options: {
        mangle:false,
      },
      lang:{
        src:['<%= dirs.jsSrc %>/lang.js'],
        dest:'<%= dirs.jsDest %>/lang.min.js'
      }, 
      plugins: {
        src: ['<%= dirs.jsCompiled %>/plugins.js'],
        dest: '<%= dirs.jsDest %>/plugins.min.js'
      },
      app:{
        src: ['<%= dirs.jsCompiled %>/app.js'],
        dest: '<%= dirs.jsDest %>/app.min.js'
      }
    },
    concurrent:{
      target:{
        tasks:['sftp-deploy:build_fi','sftp-deploy:build_se','sftp-deploy:build_dk','sftp-deploy:build_no'],
        options: {
                logConcurrentOutput: true
            }
      }
    },
  /*  jsdoc : {
        dist : {
            src: ['compiled/all.js'], 
            options: {
                destination: 'doc'
            }
        }
    },*/
    ngdocs:{
      options:{
        dest:'docs',
        scripts:['compiled/js/all.js'],
        html5Mode:true,
        title:'MyRealLondon Documentation'
      },
      all:{
        src:['public/js/modules/general.module.js','public/js/modules/system.module.js','public/js/modules/gmaps.modules.js','public/js/directives/general/experienceboxguide.directive.js']
      }
    },
    phpdocumentor: {
        dist: {
            options: {
                directory : 'app/models',
                target : 'phpdocs'
            }
        }
    },
    copy:{
      target:{
        files:[
        {
          expand:true,
          src:['public/images/**'],
          dest:'deploy/',
        },
        {
          expand:true,
          src:['app/**'],
          dest:'deploy/',
        },
        {
          expand:true,
          src:['bootstrap/**'],
          dest:'deploy/',
        },
        {
          expand:true,
          src:['vendor/**'],
          dest:'deploy/'
        },
        {
          expand:true,
          src:['public/css/**'],
          dest:'deploy/'
        },
        {
          expand:true,
          src:['public/stylesheets/**'],
          dest:'deploy/'
        },
        {
          expand:true,
          src:['public/fonts/**'],
          dest:'deploy/'
        },
        {
          expand:true,
          src:['public/templates/**'],
          dest:'deploy/'
        },
        {
          expand:true,
          src:['public/js/apps.min.js','public/js/lang.min.js'],
          dest:'deploy/',
          filter:'isFile'
        },
        {
          expand:true,
          src:['artisan','composer.json','composer.lock','app.yaml','server.php'],
          dest:'deploy/',
          filter:'isFile'
        }
        ]
      },
      copy_deploy:{
        files:[{
          expand:true,
          src:'deploy/**/*',
          dest:'deploy_fi'
        },
        {
          expand:true,
          src:'deploy/**/*',
          dest:'deploy_se'
        },
        {
          expand:true,
          src:'deploy/**/*',
          dest:'deploy_dk'
        },
        {
          expand:true,
          src:'deploy/**/*',
          dest:'deploy_no'
        }]
      },
      copy_fi:{
        files:[
        {
          src:'temp/SeedUsersTable_fi.php',
          dest:'deploy_fi/deploy/app/database/seeds/SeedUsersTable.php'
        },
        {
          src:'temp/SeedExperienceTable_fi.php',
          dest:'deploy_fi/deploy/app/database/seeds/SeedExperiencesTable.php'
        }]
      },
      copy_dk:{
        files:[
        {
          src:'temp/SeedUsersTable_dk.php',
          dest:'deploy_dk/deploy/app/database/seeds/SeedUsersTable.php'
        },
        {
          src:'temp/SeedExperienceTable_dk.php',
          dest:'deploy_dk/deploy/app/database/seeds/SeedExperiencesTable.php'
        }]
      },
      copy_se:{
        files:[
        {
          src:'temp/SeedUsersTable_se.php',
          dest:'deploy_se/deploy/app/database/seeds/SeedUsersTable.php'
        },
        {
          src:'temp/SeedExperienceTable_se.php',
          dest:'deploy_se/deploy/app/database/seeds/SeedExperiencesTable.php'
        }]
      },
      copy_no:{
        files:[
        {
          src:'temp/SeedUsersTable_no.php',
          dest:'deploy_no/deploy/app/database/seeds/SeedUsersTable.php'
        },
        {
          src:'temp/SeedExperienceTable_no.php',
          dest:'deploy_no/deploy/app/database/seeds/SeedExperiencesTable.php'
        }]
      },
      copy_en:{
        files:[
        {
          src:'temp/SeedUsersTable_en.php',
          dest:'app/database/seeds/SeedUsersTable.php'
        },
        {
          src:'temp/SeedExperienceTable_en.php',
          dest:'app/database/seeds/SeedExperiencesTable.php'
        }]
      }
    },

    secret:grunt.file.readJSON('secret.json'),

    ssh_deploy:{
      fi:{
        options:{
          host:'<%= secret.production.host %>',
          username:'<%= secret.production.username %>',
          password:'<%= secret.production.password %>',
          port:'<%= secret.production.port %>',
          deploy_path:"/mnt/mrlvolume1/public_html/myreallondon.expedia.fi/public/stylesheets",
          local_path:'../stylesheets'
        }
      }
    },
    'sftp-deploy':{
      'build':{
        auth:{
          host:'162.13.183.43',
          port:22,
          authKey:'key1'
        },
        catch:false,
        src:'deploy',
        concurrency:10,
        serverSep:'/',
        progress:true,
        dest:'/mnt/mrlvolume1/public_html/myreallondon.expedia.co.uk'
      },
      'build_fi':{
        auth:{
          host:'162.13.183.43',
          port:22,
          authKey:'key1'
        },
        catch:false,
        src:'deploy_fi/deploy',
        concurrency:10,
        serverSep:'/',
        progress:true,
        dest:'/mnt/mrlvolume1/public_html/myreallondon.expedia.fi'
      },
      'build_se':{
        auth:{
          host:'162.13.183.43',
          port:22,
          authKey:'key1'
        },
        catch:false,
        src:'deploy_se/deploy',
        concurrency:10,
        serverSep:'/',
        progress:true,
        dest:'/mnt/mrlvolume1/public_html/myreallondon.expedia.se'
      },
      'build_no':{
        auth:{
          host:'162.13.183.43',
          port:22,
          authKey:'key1'
        },
        catch:false,
        src:'deploy_no/deploy',
        concurrency:10,
        serverSep:'/',
        progress:true,
        dest:'/mnt/mrlvolume1/public_html/myreallondon.expedia.no'
      },
      'build_dk':{
        auth:{
          host:'162.13.183.43',
          port:22,
          authKey:'key1'
        },
        catch:false,
        src:'deploy_dk/deploy',
        concurrency:10,
        serverSep:'/',
        progress:true,
        dest:'/mnt/mrlvolume1/public_html/myreallondon.expedia.dk'
      }
    },
    replace:{
      mail_fi:{
        src:'temp/mail.php',
        dest:'deploy_fi/deploy/app/config/mail.php',
        replacements:[{
          from:/__MAIL__/g,
          to:'mrl_fi@expediamails.com'
        },{
          from:/__USERNAME__/g,
          to:'mrl_fi@expediamails.com'
        },
        {
          from:/__PASSWORD__/g,
          to:'expediamailscom_FW12L2'
        }]
      },
      db_fi:{
        src:'temp/database.php',
        dest:'deploy_fi/deploy/app/config/database.php',
        replacements:[{
          from:/__DB__/g,
          to:'mrl_fi'
        }]
      },
      expedia_fi:{
        src:'temp/expedia.php',
        dest:'deploy_fi/deploy/app/config/expedia.php',
        replacements:[{
          from:/__URL__/g,
          to:'http://www.expedia.fi'
        },{
          from:/__ADMINEMAIL__/g,
          to:'info@myreallondon.expedia.fi'
        },{
          from:/__TERMS__/g,
          to:'p/support/kayttoehdot'
        },{
          from:/__PRIVACY__/g,
          to:'p/support/privacy'
        },{
          from:/__HOTELS__/g,
          to:'http://www.expedia.fi/Lontoo-Hotellit.d178279.Matkaoppaat-hotellit'
        },{
          from:/__PACKAGES__/g,
          to:''
        },{
          from:/__FLIGHTS__/g,
          to:''
        },{
          from:/__LASTMINUTE__/g,
          to:''
        },{
          from:/__SITENAME__/g,
          to:'MyRealLondon'
        },{
          from:/__TRACKINGCODE__/g,
          to:'UA-52719434-1'
        },{
          from:/__LOCALE__/g,
          to:'fi_FI'
        },{
          from:/__TWITTER__/g,
          to:'Expedia'
        },{
          from:/__FACEBOOK__/g,
          to:'https://www.facebook.com/Expedia.co.uk'
        },{
          from:/__GPLUS__/g,
          to:'https://plus.google.com/+expediauk/posts'
        }]
      },
      db_local:{
        src:'temp/database.php',
        dest:'app/config/database.php',
        replacements:[{
          from:/__DB__/g,
          to:'ex_london'
        }]
      },
      expedia_en:{
        src:'temp/expedia.php',
        dest:'app/config/expedia.php',
        replacements:[{
          from:/__URL__/g,
          to:'http://www.expedia.co.uk'
        },{
          from:/__ADMINEMAIL__/g,
          to:'info@myreallondon.expedia.co.uk'
        },{
          from:/__TERMS__/g,
          to:'p/support/termsofuse'
        },{
          from:/__PRIVACY__/g,
          to:'p/support/privacy'
        },{
          from:/__SITENAME__/g,
          to:'MyRealLondon'
        },{
          from:/__HOTELS__/g,
          to:'http://www.expedia.co.uk/London-Hotels.d178279.Travel-Guide-Hotels'
        },{
          from:/__LASTMINUTE__/g,
          to:'http://www.expedia.co.uk/last-minute-deals'
        },{
          from:/__PACKAGES__/g,
          to:'http://www.expedia.co.uk/London.d178279.Holidays-City-Breaks'
        },{
          from:/__FLIGHTS__/g,
          to:'http://www.expedia.co.uk/Cheap-Flights-To-London.d178279.Travel-Guide-Flights'
        },{
          from:/__TRACKINGCODE__/g,
          to:'UA-52719434-1'
        },{
          from:/__LOCALE__/g,
          to:'en_UK'
        },{
          from:/__TWITTER__/g,
          to:'Expedia'
        },{
          from:/__FACEBOOK__/g,
          to:'https://www.facebook.com/Expedia.co.uk'
        },{
          from:/__GPLUS__/g,
          to:'https://plus.google.com/+expediauk/posts'
        }]
      },
      db_dk:{
        src:'temp/database.php',
        dest:'deploy_dk/deploy/app/config/database.php',
        replacements:[{
          from:/__DB__/g,
          to:'mrl_dk'
        }]
      },
      mail_dk:{
        src:'temp/mail.php',
        dest:'deploy_dk/deploy/app/config/mail.php',
         replacements:[{
          from:/__MAIL__/g,
          to:'mrl_dk@expediamails.com'
        },{
          from:/__USERNAME__/g,
          to:'mrl_dk@expediamails.com'
        },
        {
          from:/__PASSWORD__/g,
          to:'expediamailscom_DK76H1'
        }]
      },
      expedia_dk:{
        src:'temp/expedia.php',
        dest:'deploy_dk/deploy/app/config/expedia.php',
        replacements:[{
          from:/__URL__/g,
          to:'http://www.expedia.dk'
        },{
          from:/__ADMINEMAIL__/g,
          to:'info@myreallondon.expedia.dk'
        },{
          from:/__SITENAME__/g,
          to:'MyRealLondon'
        },{
          from:/__TRACKINGCODE__/g,
          to:'UA-52714958-1'
        },{
          from:/__LOCALE__/g,
          to:'da_DK'
        },{
          from:/__LASTMINUTE__/g,
          to:'http://www.expedia.dk/vc/billige-afbudsrejser/london'
        },{
          from:/__HOTELS__/g,
          to:'http://www.expedia.dk/London-Hoteller.d178279.Rejse-Guide-Hoteller'
        },{
          from:/__PACKAGES__/g,
          to:'http://www.expedia.dk/London.d178279.Rejser'
        },{
          from:/__FLIGHTS__/g,
          to:'http://www.expedia.dk/Fly-Til-London.d178279.Rejse-Guide-Fly'
        },{
          from:/__TWITTER__/g,
          to:'ExpediaDK'
        },{
          from:/__TERMS__/g,
          to:'p/support/termsofuse'
        },{
          from:/__PRIVACY__/g,
          to:'p/support/privacy'
        },{
          from:/__FACEBOOK__/g,
          to:'https://www.facebook.com/Expedia.dk'
        },{
          from:/__GPLUS__/g,
          to:'https://plus.google.com/+expediadk/posts'
        }]
      },
      db_se:{
        src:'temp/database.php',
        dest:'deploy_se/deploy/app/config/database.php',
        replacements:[{
          from:/__DB__/g,
          to:'mrl_se'
        }]
      },
       mail_se:{
        src:'temp/mail.php',
        dest:'deploy_se/deploy/app/config/mail.php',
        replacements:[{
          from:/__MAIL__/g,
          to:'mrl_se@expediamails.com'
        },{
          from:/__USERNAME__/g,
          to:'mrl_se@expediamails.com'
        },
        {
          from:/__PASSWORD__/g,
          to:'expediamailscom_SE51R2'
        }]
      },
      expedia_se:{
        src:'temp/expedia.php',
        dest:'deploy_se/deploy/app/config/expedia.php',
        replacements:[{
          from:/__URL__/g,
          to:'http://www.expedia.se'
        },{
          from:/__ADMINEMAIL__/g,
          to:'info@myreallondon.expedia.se'
        },{
          from:/__SITENAME__/g,
          to:'MyRealLondon'
        },{
          from:/__LASTMINUTE__/g,
          to:'http://www.expedia.se/vc/last-minute/london'
        },{
          from:/__HOTELS__/g,
          to:'http://www.expedia.se/London-Hotell.d178279.Reseguide-Hotell'
        },{
          from:/__PACKAGES__/g, 
          to:'http://www.expedia.se/London.d178279.Resor'
        },{
          from:/__FLIGHTS__/g,
          to:'http://www.expedia.se/Flyg-Till-London.d178279.Reseguide-Flyg'
        },{
          from:/__TRACKINGCODE__/g,
          to:'UA-52719145-1'
        },{
          from:/__TERMS__/g,
          to:'p/support/termsofuse'
        },{
          from:/__PRIVACY__/g,
          to:'p/support/privacy'
        },{
          from:/__LOCALE__/g,
          to:'da_DK'
        },{
          from:/__TWITTER__/g,
          to:'ExpediaSE'
        },{
          from:/__FACEBOOK__/g,
          to:'https://www.facebook.com/Expedia.se'
        },{
          from:/__GPLUS__/g,
          to:'https://plus.google.com/+expediase/videos'
        }]
      },
       mail_no:{
        src:'temp/mail.php',
        dest:'deploy_no/deploy/app/config/mail.php',
        replacements:[{
          from:/__MAIL__/g,
          to:'mrl_no@expediamails.com'
        },{
          from:/__USERNAME__/g,
          to:'mrl_no@expediamails.com'
        },
        {
          from:/__PASSWORD__/g,
          to:'expediamailscom_NP44B3'
        }]
      },
      db_no:{
        src:'temp/database.php',
        dest:'deploy_no/deploy/app/config/database.php',
        replacements:[{
          from:/__DB__/g,
          to:'mrl_no'
        }]
      },
      expedia_no:{
        src:'temp/expedia.php',
        dest:'deploy_no/deploy/app/config/expedia.php',
        replacements:[{
          from:/__URL__/g,
          to:'http://www.expedia.no'
        },{
          from:/__ADMINEMAIL__/g,
          to:'info@myreallondon.expedia.no'
        },{
          from:/__SITENAME__/g,
          to:'MyRealLondon'
        },{
          from:/__LASTMINUTE__/g,
          to:'http://www.expedia.no/vc/billige-restplasser/london'
        },{
          from:/__TRACKINGCODE__/g,
          to:'UA-52718044-1'
        },{
          from:/__HOTELS__/g,
          to:'http://www.expedia.no/London-Hoteller.d178279.Reise-Guide-Hoteller'
        },{
          from:/__PACKAGES__/g,
          to:'http://www.expedia.no/London.d178279.Reise'
        },{
          from:/__FLIGHTS__/g,
          to:'http://www.expedia.no/Fly-Til-London.d178279.Reise-Guide-Fly'
        },{
          from:/__TERMS__/g,
          to:'p/support/termsofuse'
        },{
          from:/__PRIVACY__/g,
          to:'p/support/privacy'
        },{
          from:/__LOCALE__/g,
          to:'nn_NO'
        },{
          from:/__TWITTER__/g,
          to:'ExpediaNO'
        },{
          from:/__FACEBOOK__/g,
          to:'https://www.facebook.com/Expedia.no'
        },{
          from:/__GPLUS__/g,
          to:'https://plus.google.com/+expediano/videos'
        }]
      },
      db_en:{
        src:'temp/database.php',
        dest:'app/config/database.php',
        replacements:[{
          from:/__DB__/g,
          to:'mrl_en'
        }]
      },

      locale_en:{
        src:'temp/app.php',
        dest:'app/config/app.php',
        replacements:[{
          from:/__LOCALE__/g,
          to:'en'
        },{
          from:/__URL__/g,
          to:'http://myreallondon.expedia.co.uk'
        },{
          from:/__TWITTER__/g,
          to:'ExpediaUK'
        },{
          from:/__TIMEZONE__/g,
          to:'Europe/London'
        }]
      },
      mail_en:{
        src:'temp/mail.php',
        dest:'deploy_en/deploy/app/config/mail.php',
        replacements:[{
          from:/__EXPEDIAURL__/g,
          to:'expedia.en'
        },{
          from:/__MRLURL__/g,
          to:'myreallondon.expedia.en'
        }]
      },
      expedia_en:{
        src:'temp/expedia.php',
        dest:'app/config/expedia.php',
        replacements:[{
          from:/__URL__/g,
          to:'http://www.expedia.co.uk'
        },{
          from:/__ADMINEMAIL__/g,
          to:'info@myreallondon.expedia.co.uk'
        },{
          from:/__TERMS__/g,
          to:'p/support/termsofuse'
        },{
          from:/__PRIVACY__/g,
          to:'p/support/privacy'
        },{
          from:/__SITENAME__/g,
          to:'MyRealLondon'
        },{
          from:/__TRACKINGCODE__/g,
          to:'UA-52718044-1'
        },{
          from:/__LOCALE__/g,
          to:'en_UK'
        },{
          from:/__FACEBOOK__/g,
          to:'https://www.facebook.com/Expedia.co.uk'
        },{
          from:/__GPLUS__/g,
          to:'https://plus.google.com/+expediauk/posts'
        }]
      },
      locale_local:{
        src:'temp/app.php',
        dest:'app/config/app.php',
        replacements:[{
          from:/__LOCALE__/g,
          to:'en'
        },{
          from:/__URL__/g,
          to:'http://my.lon'
        },{
          from:/__TIMEZONE__/g,
          to:'Europe/London'
        }]
      },
      locale_dk:{
        src:'temp/app.php',
        dest:'deploy_dk/deploy/app/config/app.php',
        replacements:[{
          from:/__LOCALE__/g,
          to:'dk'
        },{
          from:/__URL__/g,
          to:'http://myreallondon.expedia.dk'
        },{
          from:/__TIMEZONE__/g,
          to:'Europe/Copenhagen'
        }]
      },
      locale_se:{
        src:'temp/app.php',
        dest:'deploy_se/deploy/app/config/app.php',
        replacements:[{
          from:/__LOCALE__/g,
          to:'se'
        },{
          from:/__URL__/g,
          to:'http://myreallondon.expedia.se'
        },{
          from:/__TIMEZONE__/g,
          to:'Europe/Stockholm'
        }]
      },
      locale_no:{
        src:'temp/app.php',
        dest:'deploy_no/deploy/app/config/app.php',
        replacements:[{
          from:/__LOCALE__/g,
          to:'no'
        },{
          from:/__URL__/g,
          to:'http://myreallondon.expedia.no'
        },{
          from:/__TIMEZONE__/g,
          to:'Europe/Oslo'
        }]
      },
      locale_fi:{
        src:'temp/app.php',
        dest:'deploy_fi/deploy/app/config/app.php',
        replacements:[{
          from:/__LOCALE__/g,
          to:'fi'
        },{
          from:/__URL__/g,
          to:'http://myreallondon.expedia.fi'
        },{
          from:/__TIMEZONE__/g,
          to:'Europe/Athens'
        }]
      },
    }
  });

  // Load the plugin that provides the "uglify" task.
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-ssh-deploy');
  grunt.loadNpmTasks('grunt-sftp-deploy');
  grunt.loadNpmTasks('grunt-file-creator');
  grunt.loadNpmTasks('grunt-text-replace');
  grunt.loadNpmTasks('grunt-jsdoc');
  grunt.loadNpmTasks('grunt-ngdocs');
  grunt.loadNpmTasks('grunt-phpdocumentor');
  grunt.loadNpmTasks('grunt-concurrent');



  // Default task(s).
  grunt.registerTask('default', ['clean','concat:lib','concat:plugins',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:dev', 'uglify:lang','uglify:plugins','ngdocs:all',
    'replace:db_local','replace:expedia_local',
    'replace:locale_local','copy:target','copy:copy_en']);

  grunt.registerTask('dep', ['clean','concat:lib','concat:plugins',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:deploy', 'uglify:lang','uglify:plugins','ngdocs:all',
    'uglify:app',
    'copy:target','copy:copy_deploy','copy:copy_fi','copy:copy_dk',
    'copy:copy_no','copy:copy_se',
    'replace:db_fi','replace:expedia_fi','replace:locale_fi','replace:mail_fi',
    'replace:db_se','replace:expedia_se','replace:locale_se','replace:mail_se',
    'replace:db_no','replace:locale_no','replace:expedia_no','replace:mail_no',
    'replace:db_dk','replace:locale_dk','replace:expedia_dk','replace:mail_dk',
    'concurrent']);

  grunt.registerTask('deploy', ['clean','concat:lib','concat:jquery',
    'concat:angularShim','concat:angular','concat:ngmodules',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:all','ngdocs:all','uglify',
    'copy:target','copy:copy_deploy','copy:copy_fi','copy:copy_dk',
    'copy:copy_no','copy:copy_se',
    'replace:db_fi','replace:expedia_fi','replace:locale_fi','replace:mail_fi',
    'replace:db_se','replace:expedia_se','replace:locale_se','replace:mail_se',
    'replace:db_no','replace:locale_no','replace:expedia_no','replace:mail_no',
    'replace:db_dk','replace:locale_dk','replace:expedia_dk','replace:mail_dk',
    'concurrent' ]);

  grunt.registerTask('deploy_fi', ['clean','concat:lib','concat:jquery',
    'concat:angularShim','concat:angular','concat:ngmodules',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:all','ngdocs:all','uglify',
    'copy:target','copy:copy_deploy','copy:copy_fi','replace:db_fi','replace:expedia_fi',
    'replace:locale_fi','sftp-deploy:build_fi' ]);
  grunt.registerTask('deploy_se', ['clean','concat:lib','concat:jquery',
    'concat:angularShim','concat:angular','concat:ngmodules',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:all','ngdocs:all','uglify',
    'copy:target','copy:copy_deploy','copy:copy_se','replace:db_se','replace:expedia_se',
    'replace:locale_se','sftp-deploy:build_se' ]);
  grunt.registerTask('deploy_no', ['clean','concat:lib','concat:jquery',
    'concat:angularShim','concat:angular','concat:ngmodules',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:all','ngdocs:all','uglify',
    'copy:target','copy:copy_deploy','copy:copy_no','replace:db_no','replace:locale_no',
    'replace:expedia_no','sftp-deploy:build_no' ]);
  grunt.registerTask('deploy_dk', ['clean','concat:lib','concat:jquery',
    'concat:angularShim','concat:angular','concat:ngmodules',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:all','ngdocs:all','uglify',
    'copy:target','copy:copy_deploy','copy:copy_dk','replace:db_dk','replace:locale_dk',
    'replace:expedia_dk','sftp-deploy:build_dk' ]);
  grunt.registerTask('deploy_en', ['clean','concat:lib','concat:jquery',
    'concat:angularShim','concat:angular','concat:ngmodules',
    'concat:modules','concat:services','concat:controllers',
    'concat:directives','concat:all','ngdocs:all','uglify',
    'copy:target','copy:copy_deploy','copy:copy_en','replace:db_en','replace:locale_en',
    'replace:expedia_en','sftp-deploy:build_en' ]);

};